version: "3.7"
services:
  redis:
    image: redis
    environment:
      PORT: 6379
    ports:
      - "6379:6379"
  server:
    image: debianbuster-slim_debianruntime
    environment:
      HOST: 0.0.0.0
      PORT: 50051
      REDIS_URL: redis://default:redispw@redis:6379
    ports:
      - "8080:50051"
    depends_on:
      - redis
